### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by GLking123** [hsmaan/Iniquitate#30]
Thank you for developing such a useful tool.
I would like to ask, does the installation require Snakemake, Python, and R to work together? Is there a simpler way to install? 
Thank you once again.

**Comment by hsmaan** [comment]
Hi @GLking123,

Thanks for your question! It was a bit of an oversight to not include the conda and snakemake requirements, but I've clarified the installation instructions in this PR (https://github.com/hsmaan/Iniquitate/pull/31). 

You will need only conda, mamba and Snakemake to run the pipeline. The environment that uses R and python will be installed automatically after running Snakemake (`integrate.yaml` in `workflow/envs`). The exception is the `analysis.yaml` environment, which is for analyzing the output of the pipeline - this environment is used for the analysis scripts in `workflow/analysis`. `analysis.yaml` is installed manually as its not part of the Snakemake pipeline, and instructions are available in Step 5 in the README under **Reproducing the paper analysis**. 

Please let me know if any of this was unclear, and any other issues you run into during the install. I'm working on adding a more detailed set of documentation for all files/scripts/environments. But currently the entire pipeline can be rerun with the commands in the README and the basic installs listed. If you're using the experimental custom user config approach, please let me know how that works on your end too. Thanks and hope this helps.

**Comment by GLking123** [comment]
> Hi @GLking123,
> 
> Thanks for your question! It was a bit of an oversight to not include the conda and snakemake requirements, but I've clarified the installation instructions in this PR (#31).
> 
> You will need only conda, mamba and Snakemake to run the pipeline. The environment that uses R and python will be installed automatically after running Snakemake (`integrate.yaml` in `workflow/envs`). The exception is the `analysis.yaml` environment, which is for analyzing the output of the pipeline - this environment is used for the analysis scripts in `workflow/analysis`. `analysis.yaml` is installed manually as its not part of the Snakemake pipeline, and instructions are available in Step 5 in the README under **Reproducing the paper analysis**.
> 
> Please let me know if any of this was unclear, and any other issues you run into during the install. I'm working on adding a more detailed set of documentation for all files/scripts/environments. But currently the entire pipeline can be rerun with the commands in the README and the basic installs listed. If you're using the experimental custom user config approach, please let me know how that works on your end too. Thanks and hope this helps.

Thank you for your response, it's very helpful. I'll go and give it a try.
